name: dash_test
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - click=8.1.3
  - dash=2.9.1
  - flask=2.2.3
  - flask-compress=1.13
  - importlib-metadata=6.1.0
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libuuid=2.32.1
  - libzlib=1.2.13
  - markupsafe=2.1.2
  - ncurses=6.4
  - numpy=1.24.2
  - openssl=3.1.0
  - pandas=1.5.3
  - pip=23.0.1
  - plotly=5.13.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2022.7.1
  - readline=8.2
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.41.1
  - tenacity=8.2.2
  - tk=8.6.12
  - werkzeug=2.2.3
  - wheel=0.38.4
  - xz=5.2.10
  - zipp=3.15.0
  - zlib=1.2.13
